[pytest]
pythonpath = .
markers =
    veloce: test che girano velocemente
    lento: test che girano lentamente
    unitario: test di unità isolati
    integrazione: test che richiedono risorse esterne
